baseURL = 'https://blog.klib.cn/'
languageCode = 'en-us'
title = "Hills' Blog"
theme = "hugo-toigian"
enableGitInfo = true

[params]
# Controls table of contents visibility on right side of pages
toc = true
# Enable comments (requires Disqus shortname)
comments = false

[params.author]
name = "Hills Dong"
email = ""

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[taxonomies]
  tag = "tags"
  category = "categories"

# Navigation menu
[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/posts"
  weight = 1

  [[menu.nav]]
  name = "Tags"
  url = "/tags"
  weight = 2

  [[menu.nav]]
  name = "Archives"
  url = "/archives"
  weight = 3

  [[menu.nav]]
  name = "About"
  url = "/about"
  weight = 4

[build]
  writeStats = true

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
